<?php

/* 
 * This Code was generated by Mjomba Norman.
 * The code is not limited to correction but to open to public for educational use.
 * Scruitiny and corrections are openly allowed.
 * Project intended for Open Source use.
 *  twitter: @MjombaCertfied github:mjombanorman bitbucket:mjombanorman
 */

?>
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
    <div class="panel-heading text-center">Update the reply</div>
    <div class="panel-body">

        <form action="{{route('reply.update',['id'=>$reply->id])}}" method="post">
            {{csrf_field()}}

              
    <div class="form-group">
        <label for="content">Edit the question</label>
        <textarea name="content" id="content" cols="28" class="form-control" rows="10">{{$reply->content}}</textarea>
    </div>

    <div class="form-group">
        <button class="btn btn-success pull-right" type="submit"><i class="fa fa-send"></i>Update Reply</button>
    </div>

</form>
</div>
</div>
@endsection
